# Generated by Django 4.2.23 on 2025-11-28 07:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales_hub', '0002_product_purchase_quickservicerequest_supportrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Customer phone number', max_length=20)),
                ('service_type', models.CharField(choices=[('quick-service', 'Quick Service'), ('product-service', 'Products & Packages'), ('support-service', 'Support & Contact')], help_text='Main service category', max_length=20)),
                ('specific_service', models.CharField(choices=[('puk', 'PUK Code Retrieval'), ('estatement', 'E-Statement'), ('transaction-reversal', 'Transaction Reversal'), ('locked-device', 'Locked Device Finance'), ('clearance-letter', 'Nivushe Clearance Letter'), ('data-bundle', 'Data Bundle'), ('b2b', 'B2B Packages'), ('kinara', 'Kinara Packages'), ('esim', 'eSIM Activation'), ('device-finance', 'Device Finance'), ('hbb', 'HBB Devices'), ('br-chatbot', 'BR Chatbot Assistance'), ('call', 'Call Support'), ('location', 'Visit Our Shop'), ('appointment', 'Book Appointment')], help_text='Specific service requested', max_length=30)),
                ('timeline', models.CharField(choices=[('immediate', 'Today/Right Now'), ('this-week', 'Within this week'), ('this-month', 'Within this month'), ('just-browsing', 'Just gathering information')], default='immediate', help_text='When customer wants to solve this', max_length=20)),
                ('contact_preference', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Contact about special offers', max_length=10)),
                ('lead_score', models.IntegerField(default=0, help_text='Calculated lead score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the request', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of requester', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Agent assigned to handle this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_service_requests', to='sales_hub.agent')),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='public_site_phone_n_dba7bd_idx'), models.Index(fields=['service_type', 'created_at'], name='public_site_service_ea844a_idx'), models.Index(fields=['status', 'created_at'], name='public_site_status_816c6d_idx'), models.Index(fields=['lead_score'], name='public_site_lead_sc_010147_idx')],
            },
        ),
    ]
