"""
Django settings for bluerock project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u*vgrj%wh42$ee+npr)$hga^&+#v&144i672kp)7#@vq1jn#6s'

# WhatsApp Business API Configuration
WHATSAPP_VERIFY_TOKEN = 'yasbluerock_webhook_2024'  # Webhook verification token
WHATSAPP_APP_SECRET = '436f83138eaf9976788fc3d1e7f9773b'  # Your WhatsApp App Secret from Meta (keep this secret!)
WHATSAPP_PHONE_NUMBER_ID = '725773017276883'  # Your WhatsApp Business Account Phone Number ID
WHATSAPP_ACCESS_TOKEN = 'EAALo7o1MHcUBPpbsgp8OPihu5cp4ODWpjOwTwNwuCukFbVKrZCO9VBMhxnwMplrIrAlECu9ddgwc9l2uSzdGfeylNDHkEFJ3qw8lbpV7t0pGT6vwztbFsIKiseNzYPwioZCpGz2XrVciuYF4wvCwo5jFS8aQhpPmObbIF3UIEQjfh2vvkhJdYK2w2S6M2pdKD1kDT0OO0AbytueqJbY0EtKbZCDZCZBUAC7TL3093LUS4cZAZARgS00GVfB4ZB3OfwZDZD'  # Your WhatsApp Business API access token (keep this secret!)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Security settings
ALLOWED_HOSTS = ['www.yasbluerock.shop', 'yasbluerock.shop', 'localhost', '127.0.0.1']
CSRF_TRUSTED_ORIGINS = ['https://www.yasbluerock.shop', 'https://yasbluerock.shop']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sales_hub.apps.SalesHubConfig',
    'whatsapp_webhook',
    'public_site',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bluerock.urls'

import os

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bluerock.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
